//
//  ListFoodController.swift
//  FoodsThatICanEat
//
//  Created by Hoff Henry Pereira da Silva on 20/10/2018.
//  Copyright © 2018 Hoff Henry Pereira da Silva. All rights reserved.
//

import Foundation

protocol ListFoodDelegate {
    func filteredFood()
}

struct ListFoodController {
    
    let arrayOfFoods = [
        
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Badejo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Amêijoa", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Anchova", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Enguia", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Arenque", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Atum", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Bacalhau", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Vongole", restrictionLevel: .VERDE),
        Food(dinners: ["Cozidos", "Ensopados", "Grelhados"], family: "Peixes e mariscos", foodName: "Besugo", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Cavala", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Lula", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Caranguejo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Caracol/Escargot", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Carpa", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Caviar", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Dourada", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Camarão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Lagosta", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Linguado", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Robalo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Lúcio", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Mexilhão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Merluza", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Mero", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Lingueirão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Ostra", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Percebes", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Peixe espada", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Peixe solha", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Polvo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Tamboril (Lophius)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Rodabalho/Pregado", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Salmão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Sardinha", restrictionLevel: .AMARELO),
        Food(dinners: [""], family: "Peixes e mariscos", foodName: "Sépia/Siba", restrictionLevel: .VERDE),
        
        Food(dinners: [""], family: "Carnes", foodName: "Avestruz", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Boi", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Cavalo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Cabrito", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Porco", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Codorna", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Coelho", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Cordeiro", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Javali", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Peru", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Perdiz", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Pato", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Frango", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Vitela", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Carnes", foodName: "Cervo", restrictionLevel: .VERDE),
        
        Food(dinners: [""], family: "Legumes", foodName: "Grão-de-bico", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Legumes", foodName: "Ervilhas", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Legumes", foodName: "Fava (Vicia faba)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Legumes", foodName: "Feijão branco", restrictionLevel: .VERMELHO),
        Food(dinners: [""], family: "Legumes", foodName: "Feijão Vermelho", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Legumes", foodName: "Lentilhas", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Legumes", foodName: "Soja", restrictionLevel: .AMARELO),
        
        Food(dinners: [""], family: "Produtos lácteos e ovo", foodName: "Alfa-Lactoalbumina", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Produtos lácteos e ovo", foodName: "Beta-Lactoglobulina", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Produtos lácteos e ovo", foodName: "Caseína", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Produtos lácteos e ovo", foodName: "Clara de ovo", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Produtos lácteos e ovo", foodName: "Leite/Queijo de búfalo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Produtos lácteos e ovo", foodName: "Leite/Queijo de cabra", restrictionLevel: .AMARELO),
        Food(dinners: [""], family: "Produtos lácteos e ovo", foodName: "Leite/Queijo de ovelha", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Produtos lácteos e ovo", foodName: "Leite/Queijo de vaca", restrictionLevel: .VERMELHO),
        Food(dinners: [""], family: "Produtos lácteos e ovo", foodName: "Gema de ovo", restrictionLevel: .VERDE),
        
        Food(dinners: [""], family: "Outros", foodName: "Agar Agar", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Outros", foodName: "Alga Espaguetti", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Outros", foodName: "Alga espirulina", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Outros", foodName: "Aloe vera", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Outros", foodName: "Café", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Outros", foodName: "Canela", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Outros", foodName: "Levedura de cerveja", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Outros", foodName: "Levedura de pão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Outros", foodName: "Lúpulo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Outros", foodName: "Mel", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Outros", foodName: "Cola/Noz de cola", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Outros", foodName: "Ruibarbo", restrictionLevel: .VERDE),
        
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Acelga", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Alcachofra", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Aipo (Salsão)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Batata-doce", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Beringela", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Agrião", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Brócolis", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Abobrinha", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Abóbora", restrictionLevel: .AMARELO),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Cebola", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Cogumelos", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Repolho Roxo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Couve-de-Bruxelas", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Couve-flor", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Escarola", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Escalônia", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Aspargos", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Espinafres", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Vagem", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Alface", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Nabo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Batata", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Pepino", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Pimenta (Capsicum)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Alho-poró", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Rabanete", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Beterraba", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Repolho", restrictionLevel: .AMARELO),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Rúcula", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Tomate", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Verduras e hortaliças", foodName: "Cenoura", restrictionLevel: .VERDE),
        
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Alho", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Manjericão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Alcaparra", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Anís", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Açafrão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Pimenta (Malagueta)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Coentro", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Cravo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Canola", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Cominho", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Curry", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Endro", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Estragão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Gengibre", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Ginko Biloba", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Ginseng", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Hortelã", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Menta", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Erva-Doce", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Funcho", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Louro", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Camomila", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Mostarda", restrictionLevel: .AMARELO),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Noz moscada", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Orégano", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Salsinha", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Pimentão/Paprica", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Pimenta branca/pret", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Alcaçuz", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Alecrim", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Salvia", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Chá preto", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Chá verde", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Tomilho", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Ervas e especiarias", foodName: "Baunilha", restrictionLevel: .VERDE),
        
        Food(dinners: [""], family: "Frutos secos", foodName: "Amêndoa", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Frutos secos", foodName: "Castanha de Caju", restrictionLevel: .VERMELHO),
        Food(dinners: [""], family: "Frutos secos", foodName: "Avelã", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Frutos secos", foodName: "Amendoim", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Frutos secos", foodName: "Castanha Portuguesa", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutos secos", foodName: "Noz", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutos secos", foodName: "Castanha do Para", restrictionLevel: .VERMELHO),
        Food(dinners: [""], family: "Frutos secos", foodName: "Macadâmia", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutos secos", foodName: "Uva-Passa", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutos secos", foodName: "Pinhão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutos secos", foodName: "Pistache", restrictionLevel: .AMARELO),
        
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Amaranto (Amarantus)", restrictionLevel: .AMARELO),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Arroz", restrictionLevel: .VERMELHO),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Aveia", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Cacau", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Açúcar (de cana)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Cevada (Hordeum vulgare)", restrictionLevel: .VERMELHO),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Centeio (Secale cereale)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Cuscuz", restrictionLevel: .AMARELO),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Espelta (Triticum espelta)", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Glúten", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Milho/Óleo de milho (Zea mays)", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Malte", restrictionLevel: .AMARELO),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Milhete/Painço (Panicum miliaceum)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Polenta (Polenta giallia)", restrictionLevel: .AMARELO),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Quinua (Chenopodium quinoa)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Casca de trigo", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Girassol/Óleo de girassol", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Linhaça (Linum usitatissimum)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Sêmola de trigo duro (Triticum durum)", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Gergelim (Sesamum indicum)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Mandioca (Manihot esculenta)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Transglutaminase", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Trigo (Triticum aestivum)", restrictionLevel: .LARANJA),
        Food(dinners: [""], family: "Cereais e grãos", foodName: "Trigo-sarraceno (F. esculentum)", restrictionLevel: .VERDE),
        
        Food(dinners: [""], family: "Frutas", foodName: "Abacate", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Damasco", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Alfarroba", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Mirtilo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Amora Roxa (Blueberry)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Cereja", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Ameixa", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Chufa (C. esculentus)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Coco", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Tâmara", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Framboesa", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Morango", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Romã", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Groselha negra", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Groselha Vermelha", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Goiaba", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Figo", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Kiwi", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Lima", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Limão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Lichia", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Tangerina", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Manga", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Maçã", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Pêssego", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Melão", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Amora", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Laranja", restrictionLevel: .AMARELO),
        Food(dinners: [""], family: "Frutas", foodName: "Nectarina", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Oliva/Azeite de Oliva", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Papaia", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Pêra", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Abacaxi", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Banana", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Toranja (Grapefruit)", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Melancia", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Uva Branca/Negra", restrictionLevel: .VERDE),
        Food(dinners: [""], family: "Frutas", foodName: "Amora Negra", restrictionLevel: .VERDE)
        
    ]
    
}

